# Generated by Django 4.2.5 on 2024-11-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('cost', models.IntegerField()),
                ('count', models.IntegerField()),
                ('dod', models.DateField(auto_now=True)),
            ],
        ),
    ]
